/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as DotModulesShellPagesUnauthenticatedLayoutRouteImport } from './modules/shell/pages/unauthenticated-layout'
import { Route as DotModulesShellPagesAuthenticatedFullscreenLayoutRouteImport } from './modules/shell/pages/authenticated-fullscreen-layout'
import { Route as DotModulesShellPagesAuthenticatedLayoutRouteImport } from './modules/shell/pages/authenticated-layout'
import { Route as modulesShellPagesLandingPageRouteImport } from './modules/shell/pages/landing-page'
import { Route as DotModulesAuthScreensRegisterRegisterDotscreenRouteImport } from './modules/auth/screens/register/register.screen'
import { Route as DotModulesAuthScreensLoginLoginDotscreenRouteImport } from './modules/auth/screens/login/login.screen'
import { Route as DotModulesWorkspacePagesWorkspacesDotpageRouteImport } from './modules/workspace/pages/workspaces.page'
import { Route as DotModulesSettingsPagesSettingsDotpageRouteImport } from './modules/settings/pages/settings.page'
import { Route as DotModulesProgressPagesProgressDotpageRouteImport } from './modules/progress/pages/progress.page'
import { Route as DotModulesLearningPagesMyLearningDotpageRouteImport } from './modules/learning/pages/my-learning.page'
import { Route as DotModulesFlashcardPagesFlashcardsDotpageRouteImport } from './modules/flashcard/pages/flashcards.page'
import { Route as DotModulesLearningPagesDictionaryLayoutRouteImport } from './modules/learning/pages/dictionary-layout'
import { Route as DotModulesDashboardPagesDashboardPageRouteImport } from './modules/dashboard/pages/dashboard-page'
import { Route as DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport } from './modules/workspace/pages/new-workspace.page'
import { Route as DotModulesWorkspacePagesWorkspaceSettingsDotpageRouteImport } from './modules/workspace/pages/workspace-settings.page'
import { Route as DotModulesTopicScreensTopicsTopicsDotscreenRouteImport } from './modules/topic/screens/topics/topics.screen'
import { Route as DotModulesLearningPagesStudySessionDotpageRouteImport } from './modules/learning/pages/study-session.page'
import { Route as DotModulesFlashcardPagesStudyDotpageRouteImport } from './modules/flashcard/pages/study.page'
import { Route as DotModulesFlashcardPagesStatsDotpageRouteImport } from './modules/flashcard/pages/stats.page'
import { Route as DotModulesDictionaryScreensWordSearchDotscreenRouteImport } from './modules/dictionary/screens/word-search.screen'
import { Route as DotModulesTopicScreensTopicDetailTopicDetailDotscreenRouteImport } from './modules/topic/screens/topic-detail/topic-detail.screen'
import { Route as DotModulesDictionaryScreensWordSenseDetailDotscreenRouteImport } from './modules/dictionary/screens/word-sense-detail.screen'

const DotModulesShellPagesUnauthenticatedLayoutRoute =
  DotModulesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedFullscreenLayoutRoute =
  DotModulesShellPagesAuthenticatedFullscreenLayoutRouteImport.update({
    id: '/_(authenticated-fullscreen)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedLayoutRoute =
  DotModulesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesShellPagesLandingPageRoute =
  modulesShellPagesLandingPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesAuthScreensRegisterRegisterDotscreenRoute =
  DotModulesAuthScreensRegisterRegisterDotscreenRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesAuthScreensLoginLoginDotscreenRoute =
  DotModulesAuthScreensLoginLoginDotscreenRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesWorkspacePagesWorkspacesDotpageRoute =
  DotModulesWorkspacePagesWorkspacesDotpageRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesSettingsPagesSettingsDotpageRoute =
  DotModulesSettingsPagesSettingsDotpageRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesProgressPagesProgressDotpageRoute =
  DotModulesProgressPagesProgressDotpageRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesLearningPagesMyLearningDotpageRoute =
  DotModulesLearningPagesMyLearningDotpageRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesFlashcardPagesFlashcardsDotpageRoute =
  DotModulesFlashcardPagesFlashcardsDotpageRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesLearningPagesDictionaryLayoutRoute =
  DotModulesLearningPagesDictionaryLayoutRouteImport.update({
    id: '/dictionary',
    path: '/dictionary',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesDashboardPagesDashboardPageRoute =
  DotModulesDashboardPagesDashboardPageRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesWorkspacePagesNewWorkspaceDotpageRoute =
  DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport.update({
    id: '/workspace/new',
    path: '/workspace/new',
    getParentRoute: () =>
      DotModulesShellPagesAuthenticatedFullscreenLayoutRoute,
  } as any)
const DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute =
  DotModulesWorkspacePagesWorkspaceSettingsDotpageRouteImport.update({
    id: '/workspace/settings',
    path: '/workspace/settings',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesTopicScreensTopicsTopicsDotscreenRoute =
  DotModulesTopicScreensTopicsTopicsDotscreenRouteImport.update({
    id: '/learning/topics',
    path: '/learning/topics',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesLearningPagesStudySessionDotpageRoute =
  DotModulesLearningPagesStudySessionDotpageRouteImport.update({
    id: '/learning/study',
    path: '/learning/study',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesFlashcardPagesStudyDotpageRoute =
  DotModulesFlashcardPagesStudyDotpageRouteImport.update({
    id: '/flashcards/study',
    path: '/flashcards/study',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesFlashcardPagesStatsDotpageRoute =
  DotModulesFlashcardPagesStatsDotpageRouteImport.update({
    id: '/flashcards/stats',
    path: '/flashcards/stats',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesDictionaryScreensWordSearchDotscreenRoute =
  DotModulesDictionaryScreensWordSearchDotscreenRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DotModulesLearningPagesDictionaryLayoutRoute,
  } as any)
const DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute =
  DotModulesTopicScreensTopicDetailTopicDetailDotscreenRouteImport.update({
    id: '/learning/topics/$topicId',
    path: '/learning/topics/$topicId',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesDictionaryScreensWordSenseDetailDotscreenRoute =
  DotModulesDictionaryScreensWordSenseDetailDotscreenRouteImport.update({
    id: '/senses/$senseId',
    path: '/senses/$senseId',
    getParentRoute: () => DotModulesLearningPagesDictionaryLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof modulesShellPagesLandingPageRoute
  '/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/dictionary': typeof DotModulesLearningPagesDictionaryLayoutRouteWithChildren
  '/flashcards': typeof DotModulesFlashcardPagesFlashcardsDotpageRoute
  '/learning': typeof DotModulesLearningPagesMyLearningDotpageRoute
  '/progress': typeof DotModulesProgressPagesProgressDotpageRoute
  '/settings': typeof DotModulesSettingsPagesSettingsDotpageRoute
  '/workspace': typeof DotModulesWorkspacePagesWorkspacesDotpageRoute
  '/login': typeof DotModulesAuthScreensLoginLoginDotscreenRoute
  '/register': typeof DotModulesAuthScreensRegisterRegisterDotscreenRoute
  '/dictionary/': typeof DotModulesDictionaryScreensWordSearchDotscreenRoute
  '/flashcards/stats': typeof DotModulesFlashcardPagesStatsDotpageRoute
  '/flashcards/study': typeof DotModulesFlashcardPagesStudyDotpageRoute
  '/learning/study': typeof DotModulesLearningPagesStudySessionDotpageRoute
  '/learning/topics': typeof DotModulesTopicScreensTopicsTopicsDotscreenRoute
  '/workspace/settings': typeof DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute
  '/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
  '/dictionary/senses/$senseId': typeof DotModulesDictionaryScreensWordSenseDetailDotscreenRoute
  '/learning/topics/$topicId': typeof DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesShellPagesLandingPageRoute
  '/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/flashcards': typeof DotModulesFlashcardPagesFlashcardsDotpageRoute
  '/learning': typeof DotModulesLearningPagesMyLearningDotpageRoute
  '/progress': typeof DotModulesProgressPagesProgressDotpageRoute
  '/settings': typeof DotModulesSettingsPagesSettingsDotpageRoute
  '/workspace': typeof DotModulesWorkspacePagesWorkspacesDotpageRoute
  '/login': typeof DotModulesAuthScreensLoginLoginDotscreenRoute
  '/register': typeof DotModulesAuthScreensRegisterRegisterDotscreenRoute
  '/dictionary': typeof DotModulesDictionaryScreensWordSearchDotscreenRoute
  '/flashcards/stats': typeof DotModulesFlashcardPagesStatsDotpageRoute
  '/flashcards/study': typeof DotModulesFlashcardPagesStudyDotpageRoute
  '/learning/study': typeof DotModulesLearningPagesStudySessionDotpageRoute
  '/learning/topics': typeof DotModulesTopicScreensTopicsTopicsDotscreenRoute
  '/workspace/settings': typeof DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute
  '/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
  '/dictionary/senses/$senseId': typeof DotModulesDictionaryScreensWordSenseDetailDotscreenRoute
  '/learning/topics/$topicId': typeof DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof modulesShellPagesLandingPageRoute
  '/_(authenticated)': typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(authenticated-fullscreen)': typeof DotModulesShellPagesAuthenticatedFullscreenLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/_(authenticated)/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/_(authenticated)/dictionary': typeof DotModulesLearningPagesDictionaryLayoutRouteWithChildren
  '/_(authenticated)/flashcards': typeof DotModulesFlashcardPagesFlashcardsDotpageRoute
  '/_(authenticated)/learning': typeof DotModulesLearningPagesMyLearningDotpageRoute
  '/_(authenticated)/progress': typeof DotModulesProgressPagesProgressDotpageRoute
  '/_(authenticated)/settings': typeof DotModulesSettingsPagesSettingsDotpageRoute
  '/_(authenticated)/workspace': typeof DotModulesWorkspacePagesWorkspacesDotpageRoute
  '/_(unauthenticated)/login': typeof DotModulesAuthScreensLoginLoginDotscreenRoute
  '/_(unauthenticated)/register': typeof DotModulesAuthScreensRegisterRegisterDotscreenRoute
  '/_(authenticated)/dictionary/': typeof DotModulesDictionaryScreensWordSearchDotscreenRoute
  '/_(authenticated)/flashcards/stats': typeof DotModulesFlashcardPagesStatsDotpageRoute
  '/_(authenticated)/flashcards/study': typeof DotModulesFlashcardPagesStudyDotpageRoute
  '/_(authenticated)/learning/study': typeof DotModulesLearningPagesStudySessionDotpageRoute
  '/_(authenticated)/learning/topics': typeof DotModulesTopicScreensTopicsTopicsDotscreenRoute
  '/_(authenticated)/workspace/settings': typeof DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute
  '/_(authenticated-fullscreen)/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
  '/_(authenticated)/dictionary/senses/$senseId': typeof DotModulesDictionaryScreensWordSenseDetailDotscreenRoute
  '/_(authenticated)/learning/topics/$topicId': typeof DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dictionary'
    | '/flashcards'
    | '/learning'
    | '/progress'
    | '/settings'
    | '/workspace'
    | '/login'
    | '/register'
    | '/dictionary/'
    | '/flashcards/stats'
    | '/flashcards/study'
    | '/learning/study'
    | '/learning/topics'
    | '/workspace/settings'
    | '/workspace/new'
    | '/dictionary/senses/$senseId'
    | '/learning/topics/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/flashcards'
    | '/learning'
    | '/progress'
    | '/settings'
    | '/workspace'
    | '/login'
    | '/register'
    | '/dictionary'
    | '/flashcards/stats'
    | '/flashcards/study'
    | '/learning/study'
    | '/learning/topics'
    | '/workspace/settings'
    | '/workspace/new'
    | '/dictionary/senses/$senseId'
    | '/learning/topics/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_(authenticated)'
    | '/_(authenticated-fullscreen)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/dashboard'
    | '/_(authenticated)/dictionary'
    | '/_(authenticated)/flashcards'
    | '/_(authenticated)/learning'
    | '/_(authenticated)/progress'
    | '/_(authenticated)/settings'
    | '/_(authenticated)/workspace'
    | '/_(unauthenticated)/login'
    | '/_(unauthenticated)/register'
    | '/_(authenticated)/dictionary/'
    | '/_(authenticated)/flashcards/stats'
    | '/_(authenticated)/flashcards/study'
    | '/_(authenticated)/learning/study'
    | '/_(authenticated)/learning/topics'
    | '/_(authenticated)/workspace/settings'
    | '/_(authenticated-fullscreen)/workspace/new'
    | '/_(authenticated)/dictionary/senses/$senseId'
    | '/_(authenticated)/learning/topics/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesShellPagesLandingPageRoute: typeof modulesShellPagesLandingPageRoute
  DotModulesShellPagesAuthenticatedLayoutRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  DotModulesShellPagesAuthenticatedFullscreenLayoutRoute: typeof DotModulesShellPagesAuthenticatedFullscreenLayoutRouteWithChildren
  DotModulesShellPagesUnauthenticatedLayoutRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated-fullscreen)': {
      id: '/_(authenticated-fullscreen)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedFullscreenLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesShellPagesLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(unauthenticated)/register': {
      id: '/_(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof DotModulesAuthScreensRegisterRegisterDotscreenRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotModulesAuthScreensLoginLoginDotscreenRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/workspace': {
      id: '/_(authenticated)/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof DotModulesWorkspacePagesWorkspacesDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/settings': {
      id: '/_(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DotModulesSettingsPagesSettingsDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/progress': {
      id: '/_(authenticated)/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof DotModulesProgressPagesProgressDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/learning': {
      id: '/_(authenticated)/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof DotModulesLearningPagesMyLearningDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/flashcards': {
      id: '/_(authenticated)/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof DotModulesFlashcardPagesFlashcardsDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/dictionary': {
      id: '/_(authenticated)/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DotModulesLearningPagesDictionaryLayoutRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/dashboard': {
      id: '/_(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DotModulesDashboardPagesDashboardPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated-fullscreen)/workspace/new': {
      id: '/_(authenticated-fullscreen)/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedFullscreenLayoutRoute
    }
    '/_(authenticated)/workspace/settings': {
      id: '/_(authenticated)/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof DotModulesWorkspacePagesWorkspaceSettingsDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/learning/topics': {
      id: '/_(authenticated)/learning/topics'
      path: '/learning/topics'
      fullPath: '/learning/topics'
      preLoaderRoute: typeof DotModulesTopicScreensTopicsTopicsDotscreenRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/learning/study': {
      id: '/_(authenticated)/learning/study'
      path: '/learning/study'
      fullPath: '/learning/study'
      preLoaderRoute: typeof DotModulesLearningPagesStudySessionDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/flashcards/study': {
      id: '/_(authenticated)/flashcards/study'
      path: '/flashcards/study'
      fullPath: '/flashcards/study'
      preLoaderRoute: typeof DotModulesFlashcardPagesStudyDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/flashcards/stats': {
      id: '/_(authenticated)/flashcards/stats'
      path: '/flashcards/stats'
      fullPath: '/flashcards/stats'
      preLoaderRoute: typeof DotModulesFlashcardPagesStatsDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/dictionary/': {
      id: '/_(authenticated)/dictionary/'
      path: '/'
      fullPath: '/dictionary/'
      preLoaderRoute: typeof DotModulesDictionaryScreensWordSearchDotscreenRouteImport
      parentRoute: typeof DotModulesLearningPagesDictionaryLayoutRoute
    }
    '/_(authenticated)/learning/topics/$topicId': {
      id: '/_(authenticated)/learning/topics/$topicId'
      path: '/learning/topics/$topicId'
      fullPath: '/learning/topics/$topicId'
      preLoaderRoute: typeof DotModulesTopicScreensTopicDetailTopicDetailDotscreenRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/dictionary/senses/$senseId': {
      id: '/_(authenticated)/dictionary/senses/$senseId'
      path: '/senses/$senseId'
      fullPath: '/dictionary/senses/$senseId'
      preLoaderRoute: typeof DotModulesDictionaryScreensWordSenseDetailDotscreenRouteImport
      parentRoute: typeof DotModulesLearningPagesDictionaryLayoutRoute
    }
  }
}

interface DotModulesLearningPagesDictionaryLayoutRouteChildren {
  DotModulesDictionaryScreensWordSearchDotscreenRoute: typeof DotModulesDictionaryScreensWordSearchDotscreenRoute
  DotModulesDictionaryScreensWordSenseDetailDotscreenRoute: typeof DotModulesDictionaryScreensWordSenseDetailDotscreenRoute
}

const DotModulesLearningPagesDictionaryLayoutRouteChildren: DotModulesLearningPagesDictionaryLayoutRouteChildren =
  {
    DotModulesDictionaryScreensWordSearchDotscreenRoute:
      DotModulesDictionaryScreensWordSearchDotscreenRoute,
    DotModulesDictionaryScreensWordSenseDetailDotscreenRoute:
      DotModulesDictionaryScreensWordSenseDetailDotscreenRoute,
  }

const DotModulesLearningPagesDictionaryLayoutRouteWithChildren =
  DotModulesLearningPagesDictionaryLayoutRoute._addFileChildren(
    DotModulesLearningPagesDictionaryLayoutRouteChildren,
  )

interface DotModulesShellPagesAuthenticatedLayoutRouteChildren {
  DotModulesDashboardPagesDashboardPageRoute: typeof DotModulesDashboardPagesDashboardPageRoute
  DotModulesLearningPagesDictionaryLayoutRoute: typeof DotModulesLearningPagesDictionaryLayoutRouteWithChildren
  DotModulesFlashcardPagesFlashcardsDotpageRoute: typeof DotModulesFlashcardPagesFlashcardsDotpageRoute
  DotModulesLearningPagesMyLearningDotpageRoute: typeof DotModulesLearningPagesMyLearningDotpageRoute
  DotModulesProgressPagesProgressDotpageRoute: typeof DotModulesProgressPagesProgressDotpageRoute
  DotModulesSettingsPagesSettingsDotpageRoute: typeof DotModulesSettingsPagesSettingsDotpageRoute
  DotModulesWorkspacePagesWorkspacesDotpageRoute: typeof DotModulesWorkspacePagesWorkspacesDotpageRoute
  DotModulesFlashcardPagesStatsDotpageRoute: typeof DotModulesFlashcardPagesStatsDotpageRoute
  DotModulesFlashcardPagesStudyDotpageRoute: typeof DotModulesFlashcardPagesStudyDotpageRoute
  DotModulesLearningPagesStudySessionDotpageRoute: typeof DotModulesLearningPagesStudySessionDotpageRoute
  DotModulesTopicScreensTopicsTopicsDotscreenRoute: typeof DotModulesTopicScreensTopicsTopicsDotscreenRoute
  DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute: typeof DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute
  DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute: typeof DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute
}

const DotModulesShellPagesAuthenticatedLayoutRouteChildren: DotModulesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotModulesDashboardPagesDashboardPageRoute:
      DotModulesDashboardPagesDashboardPageRoute,
    DotModulesLearningPagesDictionaryLayoutRoute:
      DotModulesLearningPagesDictionaryLayoutRouteWithChildren,
    DotModulesFlashcardPagesFlashcardsDotpageRoute:
      DotModulesFlashcardPagesFlashcardsDotpageRoute,
    DotModulesLearningPagesMyLearningDotpageRoute:
      DotModulesLearningPagesMyLearningDotpageRoute,
    DotModulesProgressPagesProgressDotpageRoute:
      DotModulesProgressPagesProgressDotpageRoute,
    DotModulesSettingsPagesSettingsDotpageRoute:
      DotModulesSettingsPagesSettingsDotpageRoute,
    DotModulesWorkspacePagesWorkspacesDotpageRoute:
      DotModulesWorkspacePagesWorkspacesDotpageRoute,
    DotModulesFlashcardPagesStatsDotpageRoute:
      DotModulesFlashcardPagesStatsDotpageRoute,
    DotModulesFlashcardPagesStudyDotpageRoute:
      DotModulesFlashcardPagesStudyDotpageRoute,
    DotModulesLearningPagesStudySessionDotpageRoute:
      DotModulesLearningPagesStudySessionDotpageRoute,
    DotModulesTopicScreensTopicsTopicsDotscreenRoute:
      DotModulesTopicScreensTopicsTopicsDotscreenRoute,
    DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute:
      DotModulesWorkspacePagesWorkspaceSettingsDotpageRoute,
    DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute:
      DotModulesTopicScreensTopicDetailTopicDetailDotscreenRoute,
  }

const DotModulesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotModulesShellPagesAuthenticatedFullscreenLayoutRouteChildren {
  DotModulesWorkspacePagesNewWorkspaceDotpageRoute: typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
}

const DotModulesShellPagesAuthenticatedFullscreenLayoutRouteChildren: DotModulesShellPagesAuthenticatedFullscreenLayoutRouteChildren =
  {
    DotModulesWorkspacePagesNewWorkspaceDotpageRoute:
      DotModulesWorkspacePagesNewWorkspaceDotpageRoute,
  }

const DotModulesShellPagesAuthenticatedFullscreenLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedFullscreenLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedFullscreenLayoutRouteChildren,
  )

interface DotModulesShellPagesUnauthenticatedLayoutRouteChildren {
  DotModulesAuthScreensLoginLoginDotscreenRoute: typeof DotModulesAuthScreensLoginLoginDotscreenRoute
  DotModulesAuthScreensRegisterRegisterDotscreenRoute: typeof DotModulesAuthScreensRegisterRegisterDotscreenRoute
}

const DotModulesShellPagesUnauthenticatedLayoutRouteChildren: DotModulesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotModulesAuthScreensLoginLoginDotscreenRoute:
      DotModulesAuthScreensLoginLoginDotscreenRoute,
    DotModulesAuthScreensRegisterRegisterDotscreenRoute:
      DotModulesAuthScreensRegisterRegisterDotscreenRoute,
  }

const DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesUnauthenticatedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesShellPagesLandingPageRoute: modulesShellPagesLandingPageRoute,
  DotModulesShellPagesAuthenticatedLayoutRoute:
    DotModulesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotModulesShellPagesAuthenticatedFullscreenLayoutRoute:
    DotModulesShellPagesAuthenticatedFullscreenLayoutRouteWithChildren,
  DotModulesShellPagesUnauthenticatedLayoutRoute:
    DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
