/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as DotModulesShellPagesUnauthenticatedLayoutRouteImport } from './modules/shell/pages/unauthenticated-layout'
import { Route as DotModulesShellPagesAuthenticatedLayoutRouteImport } from './modules/shell/pages/authenticated-layout'
import { Route as modulesShellPagesLandingPageRouteImport } from './modules/shell/pages/landing-page'
import { Route as DotModulesAuthPagesRegisterDotpageRouteImport } from './modules/auth/pages/register.page'
import { Route as DotModulesAuthPagesLoginPageRouteImport } from './modules/auth/pages/login-page'
import { Route as DotModulesDashboardPagesDashboardPageRouteImport } from './modules/dashboard/pages/dashboard-page'
import { Route as DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport } from './modules/workspace/pages/new-workspace.page'

const DotModulesShellPagesUnauthenticatedLayoutRoute =
  DotModulesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedLayoutRoute =
  DotModulesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesShellPagesLandingPageRoute =
  modulesShellPagesLandingPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesAuthPagesRegisterDotpageRoute =
  DotModulesAuthPagesRegisterDotpageRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesAuthPagesLoginPageRoute =
  DotModulesAuthPagesLoginPageRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesDashboardPagesDashboardPageRoute =
  DotModulesDashboardPagesDashboardPageRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesWorkspacePagesNewWorkspaceDotpageRoute =
  DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport.update({
    id: '/workspace/new',
    path: '/workspace/new',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof modulesShellPagesLandingPageRoute
  '/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterDotpageRoute
  '/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesShellPagesLandingPageRoute
  '/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterDotpageRoute
  '/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof modulesShellPagesLandingPageRoute
  '/_(authenticated)': typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/_(authenticated)/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/_(unauthenticated)/login': typeof DotModulesAuthPagesLoginPageRoute
  '/_(unauthenticated)/register': typeof DotModulesAuthPagesRegisterDotpageRoute
  '/_(authenticated)/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/register' | '/workspace/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/register' | '/workspace/new'
  id:
    | '__root__'
    | '/'
    | '/_(authenticated)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/dashboard'
    | '/_(unauthenticated)/login'
    | '/_(unauthenticated)/register'
    | '/_(authenticated)/workspace/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesShellPagesLandingPageRoute: typeof modulesShellPagesLandingPageRoute
  DotModulesShellPagesAuthenticatedLayoutRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  DotModulesShellPagesUnauthenticatedLayoutRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesShellPagesLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(unauthenticated)/register': {
      id: '/_(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof DotModulesAuthPagesRegisterDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotModulesAuthPagesLoginPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/dashboard': {
      id: '/_(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DotModulesDashboardPagesDashboardPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/workspace/new': {
      id: '/_(authenticated)/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
  }
}

interface DotModulesShellPagesAuthenticatedLayoutRouteChildren {
  DotModulesDashboardPagesDashboardPageRoute: typeof DotModulesDashboardPagesDashboardPageRoute
  DotModulesWorkspacePagesNewWorkspaceDotpageRoute: typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
}

const DotModulesShellPagesAuthenticatedLayoutRouteChildren: DotModulesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotModulesDashboardPagesDashboardPageRoute:
      DotModulesDashboardPagesDashboardPageRoute,
    DotModulesWorkspacePagesNewWorkspaceDotpageRoute:
      DotModulesWorkspacePagesNewWorkspaceDotpageRoute,
  }

const DotModulesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotModulesShellPagesUnauthenticatedLayoutRouteChildren {
  DotModulesAuthPagesLoginPageRoute: typeof DotModulesAuthPagesLoginPageRoute
  DotModulesAuthPagesRegisterDotpageRoute: typeof DotModulesAuthPagesRegisterDotpageRoute
}

const DotModulesShellPagesUnauthenticatedLayoutRouteChildren: DotModulesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotModulesAuthPagesLoginPageRoute: DotModulesAuthPagesLoginPageRoute,
    DotModulesAuthPagesRegisterDotpageRoute:
      DotModulesAuthPagesRegisterDotpageRoute,
  }

const DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesUnauthenticatedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesShellPagesLandingPageRoute: modulesShellPagesLandingPageRoute,
  DotModulesShellPagesAuthenticatedLayoutRoute:
    DotModulesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotModulesShellPagesUnauthenticatedLayoutRoute:
    DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
