/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as DotModulesLearningPagesDictionarySearchDotpageRouteImport } from './modules/learning/pages/dictionary-search.page'
import { Route as DotModulesShellPagesUnauthenticatedLayoutRouteImport } from './modules/shell/pages/unauthenticated-layout'
import { Route as DotModulesShellPagesAuthenticatedLayoutRouteImport } from './modules/shell/pages/authenticated-layout'
import { Route as modulesShellPagesLandingPageRouteImport } from './modules/shell/pages/landing-page'
import { Route as DotModulesAuthPagesRegisterDotpageRouteImport } from './modules/auth/pages/register.page'
import { Route as DotModulesAuthPagesLoginPageRouteImport } from './modules/auth/pages/login-page'
import { Route as DotModulesLearningPagesMyLearningDotpageRouteImport } from './modules/learning/pages/my-learning.page'
import { Route as DotModulesDashboardPagesDashboardPageRouteImport } from './modules/dashboard/pages/dashboard-page'
import { Route as DotModulesLearningPagesWordSenseDetailDotpageRouteImport } from './modules/learning/pages/word-sense-detail.page'
import { Route as DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport } from './modules/workspace/pages/new-workspace.page'

const DotModulesLearningPagesDictionarySearchDotpageRoute =
  DotModulesLearningPagesDictionarySearchDotpageRouteImport.update({
    id: '/dictionary',
    path: '/dictionary',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesUnauthenticatedLayoutRoute =
  DotModulesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedLayoutRoute =
  DotModulesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const modulesShellPagesLandingPageRoute =
  modulesShellPagesLandingPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesAuthPagesRegisterDotpageRoute =
  DotModulesAuthPagesRegisterDotpageRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesAuthPagesLoginPageRoute =
  DotModulesAuthPagesLoginPageRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesLearningPagesMyLearningDotpageRoute =
  DotModulesLearningPagesMyLearningDotpageRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesDashboardPagesDashboardPageRoute =
  DotModulesDashboardPagesDashboardPageRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesLearningPagesWordSenseDetailDotpageRoute =
  DotModulesLearningPagesWordSenseDetailDotpageRouteImport.update({
    id: '/senses/$senseId',
    path: '/senses/$senseId',
    getParentRoute: () => DotModulesLearningPagesDictionarySearchDotpageRoute,
  } as any)
const DotModulesWorkspacePagesNewWorkspaceDotpageRoute =
  DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport.update({
    id: '/workspace/new',
    path: '/workspace/new',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof modulesShellPagesLandingPageRoute
  '/dictionary': typeof DotModulesLearningPagesDictionarySearchDotpageRouteWithChildren
  '/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/learning': typeof DotModulesLearningPagesMyLearningDotpageRoute
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterDotpageRoute
  '/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
  '/dictionary/senses/$senseId': typeof DotModulesLearningPagesWordSenseDetailDotpageRoute
}
export interface FileRoutesByTo {
  '/': typeof modulesShellPagesLandingPageRoute
  '/dictionary': typeof DotModulesLearningPagesDictionarySearchDotpageRouteWithChildren
  '/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/learning': typeof DotModulesLearningPagesMyLearningDotpageRoute
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterDotpageRoute
  '/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
  '/dictionary/senses/$senseId': typeof DotModulesLearningPagesWordSenseDetailDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof modulesShellPagesLandingPageRoute
  '/_(authenticated)': typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/dictionary': typeof DotModulesLearningPagesDictionarySearchDotpageRouteWithChildren
  '/_(authenticated)/dashboard': typeof DotModulesDashboardPagesDashboardPageRoute
  '/_(authenticated)/learning': typeof DotModulesLearningPagesMyLearningDotpageRoute
  '/_(unauthenticated)/login': typeof DotModulesAuthPagesLoginPageRoute
  '/_(unauthenticated)/register': typeof DotModulesAuthPagesRegisterDotpageRoute
  '/_(authenticated)/workspace/new': typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
  '/dictionary/senses/$senseId': typeof DotModulesLearningPagesWordSenseDetailDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionary'
    | '/dashboard'
    | '/learning'
    | '/login'
    | '/register'
    | '/workspace/new'
    | '/dictionary/senses/$senseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dictionary'
    | '/dashboard'
    | '/learning'
    | '/login'
    | '/register'
    | '/workspace/new'
    | '/dictionary/senses/$senseId'
  id:
    | '__root__'
    | '/'
    | '/_(authenticated)'
    | '/_(unauthenticated)'
    | '/dictionary'
    | '/_(authenticated)/dashboard'
    | '/_(authenticated)/learning'
    | '/_(unauthenticated)/login'
    | '/_(unauthenticated)/register'
    | '/_(authenticated)/workspace/new'
    | '/dictionary/senses/$senseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  modulesShellPagesLandingPageRoute: typeof modulesShellPagesLandingPageRoute
  DotModulesShellPagesAuthenticatedLayoutRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  DotModulesShellPagesUnauthenticatedLayoutRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  DotModulesLearningPagesDictionarySearchDotpageRoute: typeof DotModulesLearningPagesDictionarySearchDotpageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DotModulesLearningPagesDictionarySearchDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof modulesShellPagesLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(unauthenticated)/register': {
      id: '/_(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof DotModulesAuthPagesRegisterDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotModulesAuthPagesLoginPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/learning': {
      id: '/_(authenticated)/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof DotModulesLearningPagesMyLearningDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/dashboard': {
      id: '/_(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DotModulesDashboardPagesDashboardPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/dictionary/senses/$senseId': {
      id: '/dictionary/senses/$senseId'
      path: '/senses/$senseId'
      fullPath: '/dictionary/senses/$senseId'
      preLoaderRoute: typeof DotModulesLearningPagesWordSenseDetailDotpageRouteImport
      parentRoute: typeof DotModulesLearningPagesDictionarySearchDotpageRoute
    }
    '/_(authenticated)/workspace/new': {
      id: '/_(authenticated)/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof DotModulesWorkspacePagesNewWorkspaceDotpageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
  }
}

interface DotModulesShellPagesAuthenticatedLayoutRouteChildren {
  DotModulesDashboardPagesDashboardPageRoute: typeof DotModulesDashboardPagesDashboardPageRoute
  DotModulesLearningPagesMyLearningDotpageRoute: typeof DotModulesLearningPagesMyLearningDotpageRoute
  DotModulesWorkspacePagesNewWorkspaceDotpageRoute: typeof DotModulesWorkspacePagesNewWorkspaceDotpageRoute
}

const DotModulesShellPagesAuthenticatedLayoutRouteChildren: DotModulesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotModulesDashboardPagesDashboardPageRoute:
      DotModulesDashboardPagesDashboardPageRoute,
    DotModulesLearningPagesMyLearningDotpageRoute:
      DotModulesLearningPagesMyLearningDotpageRoute,
    DotModulesWorkspacePagesNewWorkspaceDotpageRoute:
      DotModulesWorkspacePagesNewWorkspaceDotpageRoute,
  }

const DotModulesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotModulesShellPagesUnauthenticatedLayoutRouteChildren {
  DotModulesAuthPagesLoginPageRoute: typeof DotModulesAuthPagesLoginPageRoute
  DotModulesAuthPagesRegisterDotpageRoute: typeof DotModulesAuthPagesRegisterDotpageRoute
}

const DotModulesShellPagesUnauthenticatedLayoutRouteChildren: DotModulesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotModulesAuthPagesLoginPageRoute: DotModulesAuthPagesLoginPageRoute,
    DotModulesAuthPagesRegisterDotpageRoute:
      DotModulesAuthPagesRegisterDotpageRoute,
  }

const DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesUnauthenticatedLayoutRouteChildren,
  )

interface DotModulesLearningPagesDictionarySearchDotpageRouteChildren {
  DotModulesLearningPagesWordSenseDetailDotpageRoute: typeof DotModulesLearningPagesWordSenseDetailDotpageRoute
}

const DotModulesLearningPagesDictionarySearchDotpageRouteChildren: DotModulesLearningPagesDictionarySearchDotpageRouteChildren =
  {
    DotModulesLearningPagesWordSenseDetailDotpageRoute:
      DotModulesLearningPagesWordSenseDetailDotpageRoute,
  }

const DotModulesLearningPagesDictionarySearchDotpageRouteWithChildren =
  DotModulesLearningPagesDictionarySearchDotpageRoute._addFileChildren(
    DotModulesLearningPagesDictionarySearchDotpageRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  modulesShellPagesLandingPageRoute: modulesShellPagesLandingPageRoute,
  DotModulesShellPagesAuthenticatedLayoutRoute:
    DotModulesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotModulesShellPagesUnauthenticatedLayoutRoute:
    DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren,
  DotModulesLearningPagesDictionarySearchDotpageRoute:
    DotModulesLearningPagesDictionarySearchDotpageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
